### ISSUE TITLE
Update "About" description on github

### ISSUE THREAD

**Issue by ramarty** [worldbank/blackmarbler#2]
@g4brielvs Could we update the "About" section on Github? I think this is done through "settings", but I don't have access to that on World Bank repos.

Right now it reads:
_Create Georeferenced Rasters of Nighttime Lights from NASA Black Marble data_

Which summarizes the bm_raster function, but not bm_extract. So maybe we change to something more general -- like:

Facilitate analysis of NASA Black Marble data

https://worldbank.github.io/blackmarbler/

**Comment by ramarty** [comment]
If that makes sense, then let's make the text similar for blackmarblepy

**Comment by g4brielvs** [comment]
@ramarty I just promoted the [team permissions](https://github.com/orgs/worldbank/teams/blackmarble-team) to "Admin". It should do the trick.

**Comment by g4brielvs** [comment]
> Right now it reads: _Create Georeferenced Rasters of Nighttime Lights from NASA Black Marble data_
What about: "Georeferenced Rasters and Statistics of Nighttime Lights from NASA Black Marble"?

**Comment by ramarty** [comment]
@g4brielvs ohhh yes I like that better, let's do that!

**Comment by ramarty** [comment]
@g4brielvs Thanks for updating! I think there's currently a tiny typo (it says **C**eoreferenced ;)
