### ISSUE TITLE
Error: object 'AllAngle_Composite_Snow_Free' not found

### ISSUE THREAD

**Issue by nikosGeography** [worldbank/blackmarbler#7]
Hi, I just started using the package and I'm impressed about it's simplicity. Great work!. I am trying to download a monthly image (VNP46A3) for April 2018, and the variable I am interested in is the _AllAngle_Composite_Snow_Free_. Here is the code:

```
library(blackmarbler)
library(sf)
library(raster)
library(terra)

#### Define NASA bearer token
bearer <- "my_bearer"

### ROI
roi_sf <- st_read("path/ny_4326.shp")

### Monthly data: raster for April 2018
r_201804 <- bm_raster(roi_sf = roi_sf,
                      product_id = "VNP46A3",
                      date = "2018-04", # The day is ignored
                      variable = "AllAngle_Composite_Snow_Free",
                      quality_flag_rm = c(1, 2),
                      bearer = bearer)

```
Two questions and a recommendation:

1. Is it possible to keep the water bodies in the NTL images? If yes, how? I could fill the water bodies with 0, but that's not very safe because the images might contain non-water bodies that ha been eliminated due to poor quality pixels.
2. in the parameter `quality_flag_rm`, I want to keep only the good quality pixels (bit 0). Is this the correct way to add the vectors?

Recommendation
1. The `raster` package has been replaced from the `terra` package. Are you planning to migrate to `terra`?

Thank you.

**Comment by ramarty** [comment]
Hi @nikosGeography - Great to hear the package is useful!

1/ Good question on water bodies. I think the tricky thing here is that BlackMarble flags water bodies with a fill value. So doing the below (ie, removing `quality_flag_rm`) will only keep pixels without a fill value. Most of these should be water bodies, but others could be cases where the fill value is applied for other reasons -- but I think for the most part these will likely correspond to water).

r_201804 <- bm_raster(roi_sf = roi_sf,
                      product_id = "VNP46A3",
                      date = "2018-04", # The day is ignored
                      variable = "AllAngle_Composite_Snow_Free",
                      bearer = bearer)

2/ Yep, using `quality_flag_rm = c(1, 2)` will only keep good quality pixels. That'll remove poor-quality pixels -- for monthly/annual, (pixels based on 3 or less observations) or gap filled observations), 

And yep, good recommendation - that's on the to-do list to migrate to `terra` so aiming to get that done relatively soon!

**Comment by nikosGeography** [comment]
Thank you for your fast reply. I apologize for the misleading title, I was searching for an error online and accidentaly I pasted the error message here.

Keep up the good work guys, looking forward to the migration to `terra `and other updates. Lastly, BlackMarble's User guide (v 1.2), Table 9, it has a Land/Water mask. Maybe you could include that as well in the function `bm_raster()`? I believe it is this mask that controls if water bodies should be included or excluded from the image.

But again, that's something minor I guess. Anyway, good job again.
